#!/bin/bash

HUB_VERSION=$(cat /usr/lib/hub-version)

cat << EOF

===============================================================================
     _   _   ___  ____________ _    _  ___  ______ _____ _____
    | | | | / _ \ | ___ \  _  \ |  | |/ _ \ | ___ \_   _|  _  |
    | |_| |/ /_\ \| |_/ / | | | |  | / /_\ \| |_/ / | | | | | |
    |  _  ||  _  ||    /| | | | |/\| |  _  ||    /  | | | | | |
    | | | || | | || |\ \| |/ /\  /\  / | | || |\ \ _| |_\ \_/ /
    \_| |_/\_| |_/\_| \_|___/  \/  \/\_| |_/\_| \_|\___/ \___/

    Projects, Hardware, Tutorials, Grafana and much more!

    https://www.hardwario.com/
    https://developers.hardwario.com/
    https://forum.hardwario.com/
    https://shop.hardwario.com/

    HARDWARIO Hub ${HUB_VERSION}

    PM2 Process Manager
    ^^^^^^^^^^^^^^^^^^^
        pm2 list                      List running services
        pm2 stop bcg-ud               Stop Radio Dongle MQTT gateway
        pm2 start bcg-ud              Start Radio Dongle MQTT gateway

    HARDWARIO Firmware Tool (for Core Module and Radio Dongle flashing)
    ^^^^^^^^^^^^^^^^^^^^^^^
        bcf update                    Update firmware list from GitHub
        bcf list                      List available firmware packages
        bcf flash                     Flash firmware (--dfu for DFU mode)
        bcf help

    HARDWARIO Hub Control Tool (for Radio Dongle and node management)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        bch pairing --start           Start pairing mode
        bch pairing --stop            Stop pairing mode
        bch node list                 List paired nodes
        bch sub                       Subscribe to all MQTT messages
        bch node rename <id> <alias>  Rename node address to text alias
        bch help

===============================================================================
EOF
