#!/bin/bash

IP_ETH=$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
IP_WIFI=$(ip -4 addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

URL_NODE_RED=""

if [[ -n "$IP_ETH" ]]
then
URL_NODE_RED="http://$IP_ETH:1880/"
fi

if [[ -n "$IP_WIFI" ]]
then
URL_NODE_RED+=" http://$IP_WIFI:1880/"
fi

cat << EOF
===============================================================================
     _   _   ___  ____________ _    _  ___  ______ _____ _____
    | | | | / _ \ | ___ \  _  \ |  | |/ _ \ | ___ \_   _|  _  |
    | |_| |/ /_\ \| |_/ / | | | |  | / /_\ \| |_/ / | | | | | |
    |  _  ||  _  ||    /| | | | |/\| |  _  ||    /  | | | | | |
    | | | || | | || |\ \| |/ /\  /\  / | | || |\ \ _| |_\ \_/ /
    \_| |_/\_| |_/\_| \_|___/  \/  \/\_| |_/\_| \_|\___/ \___/

    Projects, Hardware, Tutorials, Grafana and much more!

    https://www.hardwario.com/
    https://developers.hardwario.com/
    https://forum.hardwario.com/
    https://shop.hardwario.com/

    Note: Use Node-RED to create your automation flows at:
          $URL_NODE_RED

    PM2 Process Manager
    ^^^^^^^^^^^^^^^^^^^
        pm2 list                      List running services
        pm2 stop bcg-ud               Stop USB Dongle MQTT gateway
        pm2 start bcg-ud              Start USB Dongle MQTT gateway

    HARDWARIO Firmware Tool (for Core Module and USB Dongle flashing)
    ^^^^^^^^^^^^^^^^^^^^^^^
        bcf update                    Update firmware list from GitHub
        bcf list                      List available firmware packages
        bcf flash                     Flash firmware (--dfu for DFU mode)
        bcf help

    HARDWARIO Hub Control Tool (for USB Dongle and node management)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        bch pairing --start           Start pairing mode
        bch pairing --stop            Stop pairing mode
        bch node list                 List paired nodes
        bch sub                       Subscribe to all MQTT messages
        bch node rename <id> <alias>  Rename node address to text alias
        bch help

===============================================================================

EOF
