#!/bin/bash

IP_ETH=$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
IP_WIFI=$(ip -4 addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

URL_NODE_RED=""

if [[ -n "$IP_ETH" ]]
then
URL_NODE_RED="http://$IP_ETH:1880/"
fi

if [[ -n "$IP_WIFI" ]]
then
URL_NODE_RED+=" http://$IP_WIFI:1880/"
fi

cat << EOF
===========================================================================
  _    _          _____  _______          __     _____  _____ ____
 | |  | |   /\   |  __ \|  __ \ \        / /\   |  __ \|_   _/ __ \
 | |__| |  /  \  | |__) | |  | \ \  /\  / /  \  | |__) | | || |  | |
 |  __  | / /\ \ |  _  /| |  | |\ \/  \/ / /\ \ |  _  /  | || |  | |
 | |  | |/ ____ \| | \ \| |__| | \  /\  / ____ \| | \ \ _| || |__| |
 |_|  |_/_/    \_|_|  \_|_____/   \/  \/_/    \_|_|  \_|_____\____/

Projects, Hardware, Tutorials, Grafana and much more!

https://www.hardwario.com/
https://developers.hardwario.com/
https://shop.hardwario.com/
https://forum.hardwario.com/

Note: Use Node-RED to create your automation flows at $URL_NODE_RED

PM2 Process Manager
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    pm2 list                            list running services
    pm2 stop bcg-ud                     stop USB Dongle MQTT gateway
    pm2 start bcg-ud                    start USB Dongle MQTT gateway

HARDWARIO Firmware Tool (for Core Module and USB Dongle flashing)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    bcf update                          update firmware list from GitHub
    bcf list                            list available firmware packages
    bcf flash                           flash firmware (--dfu for DFU mode)
    bcf help

HARDWARIO Hub Control Tool (for USB Dongle and HARDWARIO node management)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    bch pairing --start                 start pairing mode
    bch pairing --stop                  stop pairing mode
    bch node list                       list paired nodes
    bch sub                             subscribe to all MQTT messages
    bch node rename <id> <alias>        rename node address to text alias
    bch help

EOF
