name: main

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  VERSION: ${GITHUB_REF##*/}

jobs:
  build-lite:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup env
      run: |
        echo "VERSION=${{env.VERSION}}" >> "$GITHUB_ENV"

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: kpartx coreutils qemu-user-static zip unzip binfmt-support openssl systemd-container parted xz-utils binfmt-support qemu-user-static

    - name: Create user with specific UID
      run: |
        sudo useradd -m -s /bin/bash -u 1000 pi
        sudo passwd -d pi
        echo "User 'pi' with UID 1000 created."

    - name: Build Raspbian Lite
      env:
        NAME: hio-raspbian-bookworm-lite
        URL: https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf-lite.img.xz
        SHA256: 4fa99737265ac338a9ed0643f502246b97b928e5dfffa92939242e26e290638d
        VERSION: ${{env.VERSION}}
      run: |
        sudo -E ./build.sh

    - name: Release
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          hio-raspbian-bookworm-lite-${{env.VERSION}}.zip
          hio-raspbian-bookworm-lite-grafana-influxdb-${{env.VERSION}}.zip

  build-desktop:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup env
      run: |
        echo "VERSION=${{env.VERSION}}" >> "$GITHUB_ENV"

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: kpartx coreutils qemu-user-static zip unzip binfmt-support openssl systemd-container parted xz-utils binfmt-support qemu-user-static

    - name: Build Raspbian Desktop
      env:
        NAME: hio-raspbian-bookworm-desktop
        URL: https://downloads.raspberrypi.com/raspios_armhf/images/raspios_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf.img.xz
        SHA256: 52a807d37a894dfcb09274382762f8274c7044ce3d98040aba474e0af93b85ab
        VERSION: ${{env.VERSION}}
      run: |
        sudo -E ./build.sh

    - name: Release
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          hio-raspbian-bookworm-desktop-grafana-influxdb-${{env.VERSION}}.zip
          hio-raspbian-bookworm-desktop-${{env.VERSION}}.zip




